### ISSUE TITLE
APP11 already has data

### ISSUE THREAD

**Issue by Were42** [contentauth/c2pa-rs#167]
Hi, we have encountered bug where photos from one of our devices can´t be used by c2pa. We use c2pa rust sdk and we tested this photo with c2pa tool both reported same error and it is "not found". After closer look at other images this image has already some data written into app11 segment they are just "00 00" but other images has app11 completly empty we asume this might be the problematic area. When we strip all metadata from photo then we are able to use both our program and c2pa tool with no problem but stripping the metadata should not be needed and is not expected for proper functionality of c2pa sdk. 
### the problematic photo 
![20230102_152829 (1)](https://user-images.githubusercontent.com/50260518/212071419-ff093c22-aaf1-47da-adf5-a58c92a22f35.jpg)
### the valid photo where problems dont ocure
![20230112_105622](https://user-images.githubusercontent.com/50260518/212071439-75fbd35d-1d4c-472c-998c-c11d216594b4.jpg)
### as seen here the problematic photo has app11 data (the left one)
![image](https://user-images.githubusercontent.com/50260518/212071815-2b560245-5234-486a-bc2a-6959e723630d.png)

### we tried it with
`c2patool 20230102_152829.jpg -m test.json -o 20230102_152829.jpg -f`
testing manifest is 
`
{
    "ta_url": "http://timestamp.digicert.com",
    "claim_generator": "TestApp",
    "assertions": [
        {
            "label": "stds.schema-org.CreativeWork",
            "data": {
                "@context": "https://schema.org",
                "@type": "CreativeWork",
                "author": [
                    {
                        "@type": "Person",
                        "name": "Joe Bloggs"
                    }
                ]
            }
        }
    ]
}
`
We are certain that this problem should be handled inside rust sdk and not in our code as the library doesn´t state that this isnt valid picture. The code in our case crashes when we use manifest_store.embed(...) function and error state just not found with no helpful message or explanation
same error occurs in c2pa_tool 
![image](https://user-images.githubusercontent.com/50260518/212073187-2c597958-d0dd-4846-8b0a-68ea340bd43d.png)

for more information please contact me i am able to share more if needed.

**Comment by mauricefisher64** [comment]
In development
