### ISSUE TITLE
GJSS TEST ISSUE #3

### ISSUE THREAD

**Issue by AmyJZhao** [contentauth/c2pa-rs#170]
Description

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project CAI

**Comment by AmyJZhao** [comment]
@adobe export issue to Jira project CAI as Task

**Comment by sdemlerCAI** [comment]
Hi Amy - plz let me know when we can delete the Test Jira tickets, so they don't pollute the project database. Thanks.

**Comment by AmyJZhao** [comment]
@sdemlerCAI Sorry about that. You can delete the Test Jira tickets once they're created.
