### ISSUE TITLE
Request: Generalize support for a remote manifest store URI reference

### ISSUE THREAD

**Issue by brogdonm** [contentauth/c2pa-rs#188]
I've been working through the SDK and understanding the layout as well as learning the C2PA specification, so please bear with me if I misunderstand any of the fundamentals or fumble with the terminology.

From what I have observed, the `start_save` function in the `store` module writes a manifest store, a reference URI to a manifest store, or both to an asset. Due to the use of the `embedded_xmp` module, it's currently tied to embedding a remote manifest store URI to specific file formats like JPEG and PNG, which support XMP, limiting its reusability.

To address this, the embedding of remote manifest store URIs could be abstracted into a separate trait that defines methods for writing asset references. This approach is similar to defining IO traits in the `asset_io` module. I think this would also start to move in the right direction of supporting remote references for streaming (i.e. `start_save_stream`) assets too. For example, could have a `ManifestUriRef` trait defined in `asset_io`:

```rust
/// Interface for supporting a URI reference to an active manifest.
pub trait ManifestUriRef {
    /// Add the URI for the active manifest for the file.
    /// 
    /// ## Arguments
    /// - `asset_path`: Path to the asset to add the URI reference to
    /// - `manifest_uri`: A valid URI to the active manifest
    fn add_manifest_uri_to_file(&self, asset_path: &Path, manifest_uri: &str) -> Result<()>; 

    /// Removes the URI for the active manifest for the file.
    /// 
    /// ## Arguments
    /// - `asset_path`: Path to the asset to add the URI reference to
    fn remove_manifest_uri_from_file(&self, asset_path: &Path) -> Result<()>;
}

pub fn get_manifest_ref(ext: &str) -> Result<Box<dyn ManifestUriRef>> {
    let ext = ext.to_ascii_lowercase();
    match ext.as_ref() {
        "jpg" | "jpeg" => Ok(Box::new(JpegIO {})),
        "png" => Ok(Box::new(PngIO{})),
        "tif" | "tiff" | "dng" => Ok(Box::new(TiffIO{})),
        _ => Err(crate::error::Error::RemoteManifestNotSupported),
    }
}
```

The `embedded_xmp` functionality can then be implemented as a concrete implementation of the trait for image file formats like JPEG and PNG. This would make the `start_save` function more flexible and modular, enabling it to work with various file formats.  For example the `JpegIO` struct could implement as follows:

```rust
impl ManifestUriRef for JpegIO {
    fn add_manifest_uri_to_file(&self, asset_path: &Path, manifest_uri: &str) -> Result<()> {
        #[cfg(feature="xmp_write")]
        {
            add_manifest_uri_to_file(asset_path, manifest_uri)
        }
        #[cfg(not(feature = "xmp_write"))]
        {
            Err(crate::error::Error::MissingFeature("xmp_write"))
        }
        
    }

    fn remove_manifest_uri_from_file(&self, _asset_path: &Path) -> Result<()> {
        todo!()
    }
}
```

This would allow for the `store::start_save` to write the remote reference cleaner:

```rust
crate::claim::RemoteManifest::EmbedWithRemote(_url) => {
    get_manifest_ref(&ext)?.add_manifest_uri_to_file(dest_path, &_url)?;
    dest_path.to_path_buf()
}
```

Overall, the point is abstracting this part of the code would improve code maintainability and extensibility by separating concerns and enabling reuse of functionality.  The sample code provided was just to provide context, there may be a better way to implement said suggestions.

**Comment by gpeacock** [comment]
I like the idea of abstracting the xml implementation from the higher level concept of storing a remote url in an asset.

**Comment by brogdonm** [comment]
@gpeacock  I have a branch that added the `ManifestUriRef` to the `asset_io` module, but it felt a little strange for `store` to understand about `asset_io` when it hadn't done so before.  Is there a better way to include?

**Comment by mauricefisher64** [comment]
It is a good suggestion.  We will be implementing a similar idea.

**Comment by mauricefisher64** [comment]
Implemented

**Comment by brogdonm** [comment]
> Implemented

Thanks @mauricefisher64
