### ISSUE TITLE
Failed reading with JumbfParseError

### ISSUE THREAD

**Issue by faceless2** [contentauth/c2pa-rs#189]
The image below fails to read in c2patool with the following output
```
c2patool --info out.jpg 
[2023-02-23T17:39:43Z DEBUG c2pa::ingredient] ingredient "out.jpg"
[2023-02-23T17:39:43Z DEBUG c2pa::ingredient] ingredient JumbfParseError(UnexpectedEof)
Information for out.jpg
No C2PA Manifests
```

This is created by another C2PA API which is still under development - so I'm certainly open to the fact that the C2PA is genuinely invalid.

However the app11 marker is accepted (by jpegtran etc) and the JUMBF box hierarchy is tested by both our code (it's also a verifier, so has been run on all the public C2PA samples) and also loads without error in https://github.com/thorfdbg/codestream-parser. So I'm fairly confident at this point.

SHA256 sum of this image is 4eef35e7becaf084c205fc962448327128f7ded053c987592b04f188f711fe1a, just in case it gets mangled by github - I posted the same to the CAI Discord server, and it was certainly mangled there.

![out](https://user-images.githubusercontent.com/989243/220986698-23457f96-3848-42e8-81dc-fbd7433d9111.jpg)

**Comment by mauricefisher64** [comment]
The jumbf format is not supported.  We only support boxes with toggles 3 and 19.

**Comment by mauricefisher64** [comment]
Also you must follow the canonical naming for labels.

**Comment by mauricefisher64** [comment]
C2PA is not generic JUMBF there are some differences.

**Comment by lrosenthol** [comment]
To be specific, @faceless2 (and good to see you here and working on C2PA!), all JUMBF boxes used in C2PA require a label and so that bit must always be true (and an associated label provided).  In addition, because we use JUMBF URI's to refer to boxes throughout the system (e.g., listing assertions, references to ingredients, etc.), you also need the requestable flag(s) set - which is where @mauricefisher64 gets the value of 3 from.

However, in reviewing the spec, this is *NOT* clear and I will file and issue and fix that.

**Comment by faceless2** [comment]
@lrosenthol yes I'm here too :-) Once we get these working, integration with PDF is the next plan, although I see there are no examples of this yet to compare against. I foresee many, many questions about the interaction of PDF/C2PA signatures over the horizon once we've sorted the basics out.

Thank you both for your help here.

* the requestable flag, doh, of course - we weren't checking for it on read so didn't spot we weren't setting it. Now fixed

* "canonical naming for labels" - this is because I was using a URL for the label with the '/' characters in it. Also my bad, this is disallowed in the spec (ISO19566-5:2019):

> this value shall be stored as ISO/IEC 10646 characters in the UTF-8 encoding. Characters in the ranges U+0000 to U+001F inclusive and U+007F to U+009F inclusive, as well as the specific characters '/', ';', '?', ':' and '#', are not permitted in the label string.

I'm going to strongly suggest bringing this list into C2PA rather than relying on ISO19566 for two reasons

1. that list includes colon, and that's clearly _not_ restricted as most of the existing examples use labels of the form `contentauth:urn:uuid:04...`.
2. as references to labels are expected to be used in URLs, it should exclude U+FEFF, U+FFFF, and U+D800-U+DFFF  - you can't reference a label from `dcterms:provenance` if it consists of a character illegal in XML 1.0. If it were me, I'd consider adding all characters with Unicode class "Format" as well.


I identified two further issues which we fixed:

* instanceID is required, we were not adding it. `c2patool` fails with a cryptic "failed parsing claim CBOR" message that could perhaps be improved.
* your CBOR parser is also not looking for a key of `33` in the COSE object to mean `x5chain` - it's now defined in https://datatracker.ietf.org/doc/html/rfc9360, although as that was only published this month(!) that's fair enough. There's a note in the spec to this effect, it's published it can probably be removed.

Here's my latest effort

![out](https://user-images.githubusercontent.com/989243/221238923-b355cb31-baca-40fc-a085-69d27ec05b95.jpg)

which is only failing because of the extended-key-usage requirements in the certificate.

That's understandable and it means I'm at the final hurdle, which is great. Thanks again for your help.

**Comment by lrosenthol** [comment]
Good callout on the labels and the valid characters.  Yes, I will bring that into the C2PA spec.

On the`x5chain` issues, we already have an update to that section of the C2PA spec (based on RFC9360).  I wouldn't start using the 33 just yet, but you should be able to soon enough.

FYI

>A previous version of this specification required claim generators to write the string label `x5chain` only to avoid the unlikely possibility that the integer label 33 would not be standardized. With draft 09, integer label 33 has been standardized, and this specification now adopts it as standard, and deprecates use of the string label. Therefore:

>* Claim generators should use only the integer 33 as the label when inserting this header into a COSE signature. Claim generators may continue to write the string label `x5chain` but this behavior is now deprecated and claim generators should be updated to use the integer label only. Claim generators shall place this header only in the protected header bucket of the COSE signature as required above.
>* Validators shall accept either the string `x5chain` or the integer 33 as the label for this header. If both labels are present, validators shall use the header with the integer label 33 and ignore the header with the string `x5chain` as the label. Validators shall accept the header from either the protected or unprotected bucket, to maintain compatibility with previous versions of this specification. In compliance with <<_identity_of_signers>>, if this header appears in both the protected and unprotected buckets with the same label, a validator must reject the claim signature as malformed due to the presence of multiple credentials.
```

**Comment by lrosenthol** [comment]
>I foresee many, many questions about the interaction of PDF/C2PA signatures over the horizon once we've sorted the basics out.

FYI: I also have an updated section on PDF embedding as well forthcoming.  Currently in PR review...
