### ISSUE TITLE
Digest for Manifest referenced from ingredient doesn't compute.

### ISSUE THREAD

**Issue by faceless2** [contentauth/c2pa-rs#194]
There are a number of files in https://github.com/c2pa-org/public-testfiles/tree/main/image that refer to the manifest `contentauth:urn:uuid:04cdf4ec-f713-4e47-a8d6-7af56501ce4b` (CA.jpg) as an ingredient.

For example, here's an excerpt from the C2PA object in 
https://github.com/c2pa-org/public-testfiles/blob/main/image/jpeg/adobe-20220124-CA.jpg

```
"c2pa.ingredient": {
    "c2pa_manifest": {
        "alg": "sha256",
        "hash": "3epjVN8X1spZW0Z6TYQO/6owR7xADaDDVzeeDBOGV4g=",
        "url": "self#jumbf=/c2pa/contentauth:urn:uuid:04cdf4ec-f713-4e47-a8d6-7af56501ce4b"
     },
```

In all cases that same hash is used, which is `base64(3epjVN8X1spZW0Z6TYQO/6owR7xADaDDVzeeDBOGV4g=)` or `hex(ddea6354df17d6ca595b467a4d840effaa3047bc400da0c357379e0c13865788)`.

My problem is I can't match that to the manifest.

I'm fully aware of the digest algorithm described in https://c2pa.org/specifications/specifications/1.2/specs/C2PA_Specification.html#_hashing_jumbf_boxes

> When creating a URI reference to an assertion (i.e., as part of constructing a [Claim](https://c2pa.org/specifications/specifications/1.2/specs/C2PA_Specification.html#_claims)), a [W3C Verifiable Credential](https://c2pa.org/specifications/specifications/1.2/specs/C2PA_Specification.html#_w3c_verifiable_credentials) or other C2PA structure stored as a JUMBF box, the hash shall be performed over the contents of the structure’s JUMBF superbox, which includes both the JUMBF Description Box and all content boxes therein (but does not include the structure’s JUMBF superbox header).

That's what I'm doing, and it's matching perfectly the output from c2patool for all JUMBF box types - _except_ manifests.

In desperation I have even tried digesting various byte ranges from the C2PA object directly at to try and find one that matches that digest - none do. <strike>**There is no byte-range in the C2PA object that matches that SHA-256 digest**</strike> (edit: see next comment), which surely means there **must** be some special processing for manifest boxes going on.

The digest I am expecting is `base64(4h9T1UCSjePpgfwJddVkegL4vFKX5qRj5UYaNtTB0jA=)` or `hex(e21f53d540928de3e981fc0975d5647a02f8bc5297e6a463e5461a36d4c1d230)`, which matches the 126477 bytes starting at byte 46 of the C2PA. Here is the C2PA object I am testing, extracted from adobe-20220124-CA.jpg: [extracted-c2pa.zip](https://github.com/contentauth/c2pa-rs/files/10844101/extracted-c2pa.zip)

So I suppose I have two questions as a result:

1. is there some special processing for manifest boxes?
2. or, failing that, would it be possible to get a dump of the bytes used to generate that digest, and I can try and figure out what's going on from there.

Finally, below is the file I am trying to verify with (what I think is) the correct digest for that manifest, which is failing to verify in c2patool. It is just a repackaging of adobe-20220124-CA.jpg

![repackaged](https://user-images.githubusercontent.com/989243/221681501-9178b81c-7f9e-43f5-bfb2-2b4692db8214.jpg)

**Comment by faceless2** [comment]
After a good few hours digesting every possible byte range within the file to look for that digest, I unexpectedly found it! It matches the 773 bytes starting at byte 107646. This turns out to be the CBOR object that is the claim for that manifest.

So to recap:

For any "ingredient" assertion that contains a `c2pa_manifest` object, that object should be a `hashed-uri-map` as described in the spec: the `url` field is the url and the has is computed as follows:

*  "_the hash shall be performed over the contents of the structure’s JUMBF superbox_" as described in [7.3.1.1](https://c2pa.org/specifications/specifications/1.2/specs/C2PA_Specification.html#_hashing_jumbf_boxes)

but in c2ps-rs, the hash for this particular object is computed differently:

* the hash is computed by digesting the CBOR object contained within the second box of the `c2pa.claim` of the manifest referred to by that URL; the object described in [10.2](https://c2pa.org/specifications/specifications/1.2/specs/C2PA_Specification.html#_syntax)

I can't see any justification for this in the spec, so I presume it's a bug?

**Comment by mauricefisher64** [comment]
The old 1.0 what was just to hash the c2p.claim.  We recently added support for the box hash method for ingredients.  This change was made in PR:https://github.com/contentauth/c2pa-rs/commit/66a872d37239f7833512da725dc1a1ba4fe34ba7

Let me know if you have any issues

**Comment by faceless2** [comment]
Apologies, I didn't know about that change to the spec _or_ the library. I've been running c2patool 0.3.9, after upgrading to 0.4.0 it no long has any problems with the C2PA block we're generating (revised image below), which is now passing 100% of the tests. Thanks again.

![out](https://user-images.githubusercontent.com/989243/222779564-76f5b997-fac2-4ed2-b1b5-590b88eb3832.jpg)
