### ISSUE TITLE
C2PA-rs returns validation code assertion.dataHash.mismatch for a box hash failure instead of assertion.boxesHash.mismatch

### ISSUE THREAD

**Issue by DavidS-msft** [contentauth/c2pa-rs#328]
The C2PATool v 0.6.2 returns 
    {
      "code": "assertion.**dataHash**.mismatch",
      "url": "self#jumbf=/c2pa/urn:uuid:c1ff5172-2367-4fa0-9f4c-f6e8710900f6/c2pa.assertions/c2pa.hash.boxes",
      "explanation": "asset hash error: hash verification( Box hash name not found )"
    }

instead of 
    {
      "code": "assertion.**boxesHash**.mismatch",
      "url": "self#jumbf=/c2pa/urn:uuid:c1ff5172-2367-4fa0-9f4c-f6e8710900f6/c2pa.assertions/c2pa.hash.boxes",
      "explanation": "asset hash error: hash verification( Box hash name not found )"
    }

In addition to this change, for boxes hashes success, C2PA is adding the assertion.boxesHash.match success code in the next version to match the other hard binding success codes.

**Comment by mauricefisher64** [comment]
String have been updated.  Correct values should now be returned.
