### ISSUE TITLE
c2pa-rs incorrectly rejecting self-signed certificates

### ISSUE THREAD

**Issue by hackerfactor** [contentauth/c2pa-rs#336]
Originally submitted as an issue to c2patool: https://github.com/contentauth/c2patool/issues/152 but this looks like a bug in c2pa-rs.

c2patool cannot be used with self-signed certs because c2pa-rs rejects self-signed certs.

As noted by [Leszko](https://github.com/leszko) in https://github.com/contentauth/c2patool/issues/114, the c2pa-rs source code is written to explicitly forbid self-signed certs. (https://github.com/contentauth/c2pa-rs/blob/d9b077c8790e172d5bc9f23dc17f13df343160f1/sdk/src/cose_validator.rs#L350)

This contradicts the C2PA specification, which repeatedly mentions the use of self-signed certificates:
https://c2pa.org/specifications/specifications/1.2/specs/C2PA_Specification.html#_x_509_certificates
E.g.,
- "The presence of a self-signed certificate in the parameter MUST NOT cause the update of the set of trust anchors without some out-of-band confirmation." (permits self-signed)
- "The Authority Key Identifier extension must be present in any certificate that is not self-signed." (permits self-signed)

If you comment out the check/rejection of self-signed certs in the c2pa-rs code, then it correctly accepts self-signed certs. However, nobody else using c2patool will be able to validate it unless they apply the same patch.

Either c2pa-rs needs to be corrected to permit self-signed certs, or the C2PA specification needs to be updated to forbid self-signed certs.

**Comment by mauricefisher64** [comment]
Please read this section: https://c2pa.org/specifications/specifications/1.3/specs/C2PA_Specification.html#_certificate_trust_chain

"Only end entity certificates shall be used to sign C2PA manifests or time-stamps. A CA certificate must not be used for these purposes. Any CA certificate (where the cA boolean in the Basic Constraints extension is asserted) being used to validate a signature on a C2PA manifest, time-stamp, or OCSP response must be rejected."

Self signed certs are allowed just not for signing.  Signing can only be done by a conforming end-entity certificate.
