### ISSUE TITLE
openssl-sys locked to 0.9.92

### ISSUE THREAD

**Issue by shuklak13** [contentauth/c2pa-rs#337]
I am trying to run C2PA in an environment which uses openssl-sys=0.9.94.

However, the [C2PA Cargo locks openssl-sys to 0.9.92](https://github.com/contentauth/c2pa-rs/commit/8dc217b93bbbee643a8d5aa6b4a0f28122c6ab6d), which means I can't use the current version of C2PA in my system.

**Comment by brogdonm** [comment]
This is also hitting from updating to 0.9.96 for the openssl 0.10.60 for the latest vulnerability.

**Comment by mauricefisher64** [comment]
openssl-sys dependency has been removed.
