### ISSUE TITLE
Update openssl create, verify compatibility with OpenSSL 3.x

### ISSUE THREAD

**Issue by dkozma** [contentauth/c2pa-rs#350]
## Overview
This requires the following changes:
- Update to the latest version of the [openssl crate](https://crates.io/crates/openssl)
- Ensure we can build with OpenSSL 3.x
- Update any license files with the terms set in the Apache license (if needed)

**Comment by mauricefisher64** [comment]
SDK has been updated to use OpenSSL 3.x
