### ISSUE TITLE
MP3 support

### ISSUE THREAD

**Issue by lperichon** [contentauth/c2pa-rs#367]
Is version 0.29 on the main branch? The readme indicates its from Nov 2023, but I'm trying to use c2patool on mp3s but keep getting an error "XMP is not supported" even though I specified to use c2pa-rs main branch in the dependencies.

EDIT: More specifically, what I'm trying to do is to embed a remote manifest url on an mp3, without remote manifests it works.

**Comment by mauricefisher64** [comment]
MP3 is on the main branch.  Support for XMP (i.e.) embedding of a remote manifest URL is not supported yet.

**Comment by lperichon** [comment]
Thank you! I will keep checking and find a workaround in the meantime
