### ISSUE TITLE
es256 not supported in some js environment

### ISSUE THREAD

**Issue by clementh59** [contentauth/c2pa-rs#428]
Hi,

We built a [Chrome extension](https://chromewebstore.google.com/detail/c2pa-content-credentials/mjkaocdlpjmphfkjndocehcdhbigaafp) that automatically reads and validates C2PA manifests.

It leverages c2pa-js in the background, which uses your library.
We noticed that some COSE signatures were not validated in the extension while it was when using the same library (c2pa) with the exact same manifest in a web app.
We created an [issue](https://github.com/contentauth/c2pa-js/issues/125) in c2pa-js a few months ago.

We recently identified that the problem might come from `c2pa-rs` and not directly `c2pa-js`.
All the problematic signatures seem to use `es256`.

I provided a few examples and more context in the [other issue](https://github.com/contentauth/c2pa-js/issues/125#issuecomment-2006813235).

Regards,
Clement from Digimarc

**Comment by mauricefisher64** [comment]
I think you address the issue on your own here: https://github.com/contentauth/c2pa-js/issues/125
