### ISSUE TITLE
Data Box usage

### ISSUE THREAD

**Issue by stefanodevenuto** [contentauth/c2pa-rs#485]
Hi, I'm quite new to the C2PA specification, and while reading it I approached the concept of Data Box (https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_data_boxes).

While using this library, I couldn't find a way to create a Data Box and later reference it from an Assertion.
Is there a way to do it currently?

**Comment by gpeacock** [comment]
We are looking into a way to support this. Thank you

**Comment by mauricefisher64** [comment]
databoxes have been deprecated.  We will not be adding support
