### ISSUE TITLE
Invalid test data in json_box_reader() remains undetected

### ISSUE THREAD

**Issue by UlrichEckhardt** [contentauth/c2pa-rs#515]
Greetings!

I'm just starting into C2PA and JUMBF, so I may be mistaken. Anyhow, take a look at the byte buffer after decoding the hex string:
```none
0: 0
1: 0
2: 0
3: 90
...
8: 0
9: 0
10: 0
11: 45
...
53: 0
54: 0
55: 0
56: 38
...
```
In the above, I removed anything but the length fields of the top-level box and the nested description box and JSON box. Several observations here:

- The array contains 91 bytes, but the top-level length field only uses 90.
- The first nested box starts at offset 8. Add to that the length 45 and you arrive at 53. That part has no suprises.
- The second nested box starts at offset 53. Add to that the length 38 and you arrive at the 91. This matches the array length, but exceeds the top-level box length.

A simple fix for the test data is to change the first "a" in the hex string to a "b", changing the top-level box length to 91. However, the failure to detect this length mismatch should be considered a bug and fixed properly.

Hope that makes sense!

Uli

**Comment by mauricefisher64** [comment]
Can you provide a sample?

**Comment by mauricefisher64** [comment]
Thanks, good find.
