### ISSUE TITLE
Some functions are unavailable on WASM

### ISSUE THREAD

**Issue by ivan770** [contentauth/c2pa-rs#523]
Hi. I noticed that some of the internal functionality is unavailable on WebAssembly targets.

For instance, when trying to sign a manifest using this crate built for WASM, I get an error from the following function: https://github.com/contentauth/c2pa-rs/blob/d72c43d60b34b90c49e6b5be0ba0d4183bb3997d/sdk/src/cose_validator.rs#L1214-L1224

The exact same code built for x86_64 works fine.

I managed to make the library compile by removing some of those `#[cfg(...)]` macros, but I did not test the usability of the library in that case. Is it possible to make x86_64 and WASM equivalent in terms of supported functionality?

**Comment by mauricefisher64** [comment]
We only suppprt verify_cose_aysnc though the wasm32 path.  There are features in that code path that do not have wasm32 support that we do not yet have solutions for.

**Comment by mauricefisher64** [comment]
You can sign via the async code paths.

**Comment by mauricefisher64** [comment]
It is not a standard build we create but it should now be possible.
