### ISSUE TITLE
Panic when reading empty stream

### ISSUE THREAD

**Issue by ok-nick** [contentauth/c2pa-rs#528]
Repro:
```rust
use std::io::{self, Cursor};

use c2pa::{Builder, Reader, Result};

mod common;
use common::test_signer;

#[test]
fn test_builder_read() -> Result<()> {
    let manifest_def = include_str!("../tests/fixtures/simple_manifest.json");
    let mut source = Cursor::new(include_bytes!("fixtures/sample1.svg"));
    let format = "image/svg+xml";

    let mut builder = Builder::from_json(manifest_def)?;
    let manifest_bytes = builder.sign(&test_signer(), format, &mut source, &mut io::empty())?;

    Reader::from_manifest_data_and_stream(&manifest_bytes, format, Cursor::new(vec![]))?;

    Ok(())
}
```
Error:
```
thread 'test_builder_read' panicked at sdk/src/utils/hash_utils.rs:247:28:
attempt to subtract with overflow
```

**Comment by Coolkaba** [comment]
> Repro:
> 
> ```rust
> use std::io::{self, Cursor};
> 
> use c2pa::{Builder, Reader, Result};
> 
> mod common;
> use common::test_signer;
> 
> #[test]
> fn test_builder_read() -> Result<()> {
>     let manifest_def = include_str!("../tests/fixtures/simple_manifest.json");
>     let mut source = Cursor::new(include_bytes!("fixtures/sample1.svg"));
>     let format = "image/svg+xml";
> 
>     let mut builder = Builder::from_json(manifest_def)?;
>     let manifest_bytes = builder.sign(&test_signer(), format, &mut source, &mut io::empty())?;
> 
>     Reader::from_manifest_data_and_stream(&manifest_bytes, format, Cursor::new(vec![]))?;
> 
>     Ok(())
> }
> ```
> 
> Error:
> 
> ```
> thread 'test_builder_read' panicked at sdk/src/utils/hash_utils.rs:247:28:
> attempt to subtract with overflow
> ```

thread 'test_builder_read' panicked at sdk/src/utils/hash_utils.rs:247:28:
attempt to subtract with overflow
