### ISSUE TITLE
Remove the restriction on gix-url < 2.5.1

### ISSUE THREAD

**Issue by pierrechevalier83** [contentauth/c2pa-rs#571]
gix-url was locked to be under 2.5.1 in June: https://github.com/contentauth/c2pa-rs/commit/69ae6aa8f54ce89c490c3285f55993e3309cd250

The commit message states:
> url crate version 2.5.1 introduces new license "Unicode-3.0" which needs to be reviewed before we can accept it

I thought I would make a tracking issue for this so I can be notified when this review has taken place and the block is removed.

In the meantime, it is complicated to depend on this and other crates like `gix-url` which require `2.5.2` or above for compatibility with the nightly compiler.

**Comment by scouten-adobe** [comment]
@pierrechevalier83 the license and MSRV changes in url 2.5.1 (note: url crate, not gix-url) were problematic for us and apparently many others. Just became aware that the changes were reverted, which makes things a lot easier for us. (See discussion here: https://github.com/servo/rust-url/issues/937.) 

We just released c2pa-rs version 0.33.4. This version now requires 2.5.2 or newer and hopefully should resolve your issues.
