### ISSUE TITLE
Box hash failure reported when processing some JPEG images

### ISSUE THREAD

**Issue by mauricefisher64** [contentauth/c2pa-rs#611]
Images with RSTn listed as box names do not work.

**Comment by aliciahurst** [comment]
In our case, the issue specifically occurred with files that were originally in the HEIC format and were exported to JPG using an Apple native tool, such as Preview or the Photos app, before signing. However, HEIC images converted to JPG in Photoshop—whether using Content Credentials or converted separately and signed afterward—validated successfully.
