### ISSUE TITLE
what certificate to use for signing?

### ISSUE THREAD

**Issue by ttbuffey** [contentauth/c2pa-rs#636]
I have a PKI certificate that has below parameters.however fails in signing. I am wondering what’s the wrong?  
CA false means it is an end certificate, which is fine , right? Is the extended key usage not right？sincerely hope you can help answer.

X509v3 extensions:            
X509v3 Basic Constraints:                 
CA:FALSE           
X509v3 Key Usage: critical                
Digital Signature, Key Encipherment         
X509v3 Extended Key Usage:                 
TLS Web Client Authentication

**Comment by mauricefisher64** [comment]
You must have the correct EKUs: See: https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#x509_certificates
