### ISSUE TITLE
Can`t verify generated images

### ISSUE THREAD

**Issue by StarodubtsevDV** [contentauth/c2pa-rs#64]
Hello!

I tried to verify test image (attached to issue) generated by your`s library on this verification [site](https://verify.contentauthenticity.org/). But it failed in case of unavailable image content credentials (screenshot attached bellow).
But image verified by c2pa-tool (v 0.2.0, from this project) successfully.
Could you say what side is getting wrong: verification site or this project?

![CAI](https://user-images.githubusercontent.com/108517552/176855246-13c1f9bf-bd4a-410b-8ab7-66365e7eb86d.jpg)
![cai_verify](https://user-images.githubusercontent.com/108517552/176856343-e751a747-1d29-48f1-a033-d1401c46b3f1.PNG)

**Comment by dkozma** [comment]
@StarodubtsevDV sorry for the delay here - we just deployed an update to Verify that should resolve this. Can you please check on your end and confirm it is as you expect?

**Comment by StarodubtsevDV** [comment]
We have checked ours generated images (that was in issue), they were verified properly. Thank you so much!
We didn`t recompile library to test it`s generated images yet. We will notify you when it will be done.

**Comment by dkozma** [comment]
@StarodubtsevDV Glad to hear it works! I will close this issue for now - please open another issue if you come across anything else that looks like it is not working properly and we will investigate - thanks!
