### ISSUE TITLE
`cargo run --example client` failed

### ISSUE THREAD

**Issue by jingzhaoou** [contentauth/c2pa-rs#66]
When I ran `cargo run --example client`, I ran into the following errors:

```
$ cargo run --example client 
   Compiling c2pa v0.7.0 (/home/ec2-user/workspace/c2pa-rs/sdk)
    Finished dev [unoptimized + debuginfo] target(s) in 6.86s
     Running `target/debug/examples/client`
Error: No such file or directory (os error 2)
```

After some debugging, it occurs to me it is related to the following two lines:

https://github.com/contentauth/c2pa-rs/blob/6e1af5771d8f7ce979b5206c06f8ffb9fd1a01eb/sdk/examples/client/client.rs#L112-L113

`signcert_path` should point to the certificate `certs.ps256.pub` while `pkey_path` should point to the private key `certs.ps256.pem`. That is, things should look like 

```rust
    let signcert_path = "./sdk/tests/fixtures/certs/ps256.pub";
    let pkey_path = "./sdk/tests/fixtures/certs/ps256.pem";
```

**Comment by jingzhaoou** [comment]
Note that I also need to adjust the paths to the files for things to work.

**Comment by gpeacock** [comment]
Thank you.
This is fixed in https://github.com/contentauth/c2pa-rs/commit/ff293565bff377e9eef03624bc9503757a59c51e
