### ISSUE TITLE
Signed Image file with external reference to C2PA manifest still contains full C2PA manifest locally

### ISSUE THREAD

**Issue by nitrat7** [contentauth/c2pa-rs#756]
Signed Image file with external reference to C2PA manifest still contains full C2PA manifest locally

I'd expect in image only reference to sidecar C2PA-Manifest with given URL
https://github.com/contentauth/c2patool?tab=readme-ov-file#generating-a-remote-manifest

tested with c2patool 0.9.12 

```
./c2patool source2.jpg \
-m test.json \
-r http://testhost.com/signed.c2pa \
-f -o ext_manifest_dest.jpg

```
![ext_manifest_dest](https://github.com/user-attachments/assets/42c87f9e-f42e-4c78-9f41-978b33d4846e)
![source](https://github.com/user-attachments/assets/c03d3d80-5b6f-4252-a017-ece6a6c91409)

**Comment by mauricefisher64** [comment]
You are allowed to have both.  Just use the -r -r options.
